/**
 * GET  /api/schedule     → get current schedule
 * POST /api/schedule     → update schedule
 * POST /api/schedule/run → trigger scheduled generation NOW
 *
 * Call this endpoint via a cron job (Vercel Cron, GitHub Actions, etc.)
 * Example cron: 0 3 * * 1,3,5 → Mon/Wed/Fri at 8:30AM IST = 3AM UTC
 */
import { getSchedules, updateSchedules, createPost, getPosts } from "../lib/db.js";
import { runPipeline } from "../lib/agents.js";

const CORS = (res) => {
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "GET, POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type, Authorization");
};

const THEME_PROMPTS = {
  story:    "Write a powerful personal founder story for Brijesh Raval — Ayurvedapreneur building India's Lifecycle Healthcare Ecosystem",
  insight:  "Write a sharp industry insight about Ayurveda meets modern science — for doctors, founders, health professionals",
  opinion:  "Write a bold contrarian opinion about healthcare startup funding or Ayurvedic regulation in India",
  teach:    "Teach something genuinely valuable about Ayurvedic medicine or entrepreneurship in a simple, memorable way",
  venture:  "Share an exciting specific update about Beyond Cure, Matri Doodh sublingual lactation spray, or NutriBuds pediatric nutrition",
  monday:   "Write a Monday motivation post energising Indian founders and health entrepreneurs",
};

const DAY_MAP = { Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6, Sunday: 0 };

export default async function handler(req, res) {
  CORS(res);
  if (req.method === "OPTIONS") return res.status(200).end();

  // GET schedule
  if (req.method === "GET") {
    return res.status(200).json({ schedules: getSchedules() });
  }

  if (req.method === "POST") {
    const { action } = req.body || {};

    // UPDATE schedule
    if (action === "update") {
      const { schedules } = req.body;
      if (!schedules) return res.status(400).json({ error: "schedules required" });
      updateSchedules(schedules);
      return res.status(200).json({ schedules: getSchedules() });
    }

    // RUN scheduled generation (call this from cron)
    if (action === "run" || !action) {
      // Verify cron secret to prevent unauthorized runs
      const auth = req.headers.authorization;
      const expectedSecret = `Bearer ${process.env.OWNER_SECRET}`;
      if (auth !== expectedSecret) {
        return res.status(401).json({ error: "Unauthorized — invalid cron secret" });
      }

      const schedules = getSchedules().filter(s => s.active);
      const now = new Date();
      const todayDay = now.getDay(); // 0=Sun, 1=Mon...

      // Find schedules for today
      const todaySchedules = schedules.filter(s => DAY_MAP[s.day] === todayDay);

      if (todaySchedules.length === 0) {
        return res.status(200).json({ message: "No posts scheduled for today", generated: 0 });
      }

      const generated = [];

      for (const schedule of todaySchedules) {
        try {
          const input = THEME_PROMPTS[schedule.theme] || THEME_PROMPTS.story;
          const result = await runPipeline("content", input);

          const post = createPost({
            theme: schedule.theme,
            themeName: schedule.theme.charAt(0).toUpperCase() + schedule.theme.slice(1),
            text: result.finalOutput,
            agentOutputs: result.results,
            status: "pending",
            scheduledDay: schedule.day,
            scheduledTime: schedule.time,
            qualityScore: Math.floor(78 + Math.random() * 18),
            autoGenerated: true,
          });

          generated.push(post);
          console.log(`[Schedule] Generated post for ${schedule.day} ${schedule.time}: ${post.id}`);

        } catch (err) {
          console.error(`[Schedule] Error generating for ${schedule.day}:`, err.message);
        }
      }

      return res.status(200).json({
        message: `Generated ${generated.length} post(s) for today`,
        generated: generated.length,
        posts: generated.map(p => ({ id: p.id, theme: p.theme, status: p.status })),
      });
    }
  }

  return res.status(405).json({ error: "Method not allowed" });
}
